[tool.commitizen]
version = "0.1.0a3"
version_files = ["src/myc_http_tools/__version__.py", "pyproject.toml"]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version â†’ $new_version [skip-ci]"
